### ISSUE TITLE
Single sample 

### ISSUE THREAD

**Issue by icemduru** [jakobnissen/vamb#10]
Hi,
I want to use vamp for each sample individually. However, software throws an error:

  File "~/vamb/encode.py", line 233, in calc_loss
    ce_weight = (1 - self.alpha) / _log(self.nsamples)
ZeroDivisionError: float division by zero

Due the operation "_log(self.nsamples)" gives 0, I cannot get results.
And suggestion or solution ?

Log file:
Starting Vamb version 1.0.1
        Date and time is 2019-02-08 14:40:02.438325

Calculating TNF
        Processed 262696085 bases in 199450 sequences.
        Calculated TNF in 43.5 seconds.

Calculating RPKM
        Parsing 1 BAM files with 8 subprocesses.
        Processed  ../C102_for_vamb_sorted.bam
        Calculated RPKM in 1894.91 seconds.

Creating and training VAE
        Created VAE
        Created dataloader and mask
        Number of sequences unsuitable for encoding: 5
        Number of sequences remaining: 199445
        Network properties:
        CUDA: False
        Alpha: 0.05
        Beta: 200.0
        Dropout: 0.2
        N hidden: 325, 325
        N latent: 40

        Training properties:
        N epochs: 500
        Starting batch size: 64
        Batchsteps: 25, 75, 150, 300
        Learning rate: 0.001
        N sequences: 199445
        N samples: 1

**Comment by jakobnissen** [comment]
Dear @icemduru 

We're aware of this problem, and have fixed it on the `dev` branch. However, in order to train a single sample, we cannot use the cross entropy loss, and instead use sum of squared error for abundance. This constitutes a change in the method of VAMB, and therefore we don't want to backport the fix to the existing master branch, where we only add bugfixes until the next release.

We're in the process of testing VAMB on single-sample versus multi-sample binning. While we haven't reached a conclusion, it seems so far that METABAT2 is superior to VAMB for single samples. Although it must be said that VAMB using multiple samples is superior to either binner using single samples (this is simply because there is a *lot* of information in co-abundance).

So my suggestion is: Use multiple samples when binning. If this is not possible, use METABAT2 instead of VAMB. If you want to run VAMB anyway, use the `dev` branch.

**Comment by icemduru** [comment]
Thank you very much for the reply. 

I have used METABAT2 already, but i was curious about the VAMB results also. Since I am using several binning tools and getting "consensus" using DASTool, it would be good to run VAMB too. I will check the dev branch.
