### ISSUE TITLE
allow for input of RPKM value table

### ISSUE THREAD

**Issue by nick-youngblut** [jakobnissen/vamb#14]
It would be helpful to include the option of providing a pre-calculated table of RPKM values, given that vamb can take a long time to calculate RPKM with many (large) bam files (in my case, many days). I'd like to bypass this calculation if vamb dies during the post-RPKM calc steps.

**Comment by jakobnissen** [comment]
Dear @nick-youngblut 

I absolutely agree! That's why I implemented it on the `dev` branch in [commit 71d7e0](https://github.com/jakobnissen/vamb/commit/71d7e04f55fefb569d4913b31bf607cbc9396ee6). However, I'm a bit skittish about merging these kind of changes to the master branch, as I usually update the `dev` branch several times a week, and bugs undoubtedly sneak in. In fact, the `dev` branch probably spends most of its time with at least some features of Vamb broken due to these frequent updates.

However, we plan to release a new version of Vamb soon (around the end of March), where we merge `dev` into `master` after a period of testing. This new release will include tonnes of changes, such as a whole new clustering algorithm, new commandline options, a new benchmarking algorithm, and some other quality of life improvements.

If you don't mind the risk involved with running software from the not-quite-tested `dev` branch, you'll get these features. Alternatively, you can write a Python script where you import Vamb and do your analysis in that - then you can just choose to simply load your matrices in rather than calculating them. All the steps in the Vamb pipeline are implemented as Python functions you can call. Check `doc/tutorial.html` for how to do that.

**Comment by nick-youngblut** [comment]
Thanks for the info on the `dev` branch. I may give it a shot. 


> I usually update the dev branch several times a week, and bugs undoubtedly sneak in

Why not use continuous integration to find these bugs (eg., CircleCI)? It may be hard to get a small enough dataset to work in the time frames available via CI, but it would definitely help you in the long run (at least, CI has greatly helped my software development). 

Also, do you have plans to add vamb to bioconda? Software management via conda greatly helps with software installation, management, and documenting/recreating reproducible bioinformatics environments.

**Comment by jakobnissen** [comment]
Continuous integration is absolutely a good idea for most software. Unfortunately, Vamb is in the awkward position that it only really works with large datasets and training times. If we try to run it on a small test dataset, the training will grossly overfit and the clustering algorithm (which depends on a decent density of clusters) will not work. For example, version 1.0.0 of Vamb was actually released with a bug that silently corrupted the latent representation before clustering - due to a small "optimization" that I foolishly pushed to `master` *after* having tested Vamb and confirmed that it worked. This could only have been detected with a large dataset.
We *could* test much of the functionality of Vamb (for example, if loading in data works, and if the BAM parsing gives sensible results), I suppose, just not the actual core task of encoding and binning metagenomes. At this point, I'm dubious it's worth it, since we'd have to run it through the entire test battery anyway to ensure that the clustering peformance doesn't suffer.

Actually, we havn't thought about adding it to bioconda at all, but that sounds like a good idea. Are there any guides on how to add a package to BioConda?

**Comment by nick-youngblut** [comment]
Yeah, the large metagenome datasets can make CI a challenge. CircleCI can provide a decent amount of resources, but maybe it's not enough.

The [bioconda docs](https://bioconda.github.io/contributing.html) are pretty good for explaining how to create a bioconda recipe. It's pretty easy. It really helps if your software is set up as a python package (and on pypi), but that's not necessary.
