### ISSUE TITLE
Cannot estimate from less than nsamples contigs

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [jakobnissen/vamb#17]
Hello,
In my quest of understanding why vamb is slow on my current setup, I increased drastically the minimum size contig so that only 1000 remains : 
run.py Vamb_100000 Contigs/Contigs.fa Map/*.cram -m 100000 
It run in about one hour with 40 min on the encoding step. Then crashes with the following error message : 

Traceback (most recent call last):
  File "/home/sebr/seb/bin/run.py", line 312, in <module>
    logfile=logfile)
  File "/home/sebr/seb/bin/run.py", line 147, in main
    cluster(outdir, latent, contignames, maxclusters, minclustersize, logfile)
  File "/home/sebr/seb/bin/run.py", line 109, in cluster
    logfile=logfile, destroy=True)
  File "/mnt/gpfs/seb/Applications/vamb/cluster.py", line 223, in cluster
    labels, threshold = _check_params(matrix, threshold, labels, nsamples, maxsize, maxsteps, logfile)
  File "/mnt/gpfs/seb/Applications/vamb/cluster.py", line 171, in _check_params
    raise ValueError('Cannot estimate from less than nsamples contigs')
ValueError: Cannot estimate from less than nsamples contigs

Is it an issue with some samples not having any of theses contigs?

**Comment by jakobnissen** [comment]
Dear @Sebastien-Raguideau 

Using 40 minutes for 300 epochs, 1000 contigs is remarkably slow. After all, Vamb mostly just uses a small feedforward network. Already here the alarm bells are ringing. I don't really know what the issue could be. Are you running out of RAM, so that it runs completely in swap?
For reference, I'm now looking at one of my previous runs which did 500 epochs of 200 000 contigs in ~16 minutes. Even though you have more samples (100-ish?) than my 10, the speed difference is remarkable. I would definitely look at PyTorch itself.

The error is caused by running Vamb on less than 2500 contigs. More specifically, it is raised to `_check_params` if one tries to autodetect the clustering threshold using a randomly sampled number of contigs (default = 2500) larger than the total number of contigs.

I see the error message is not very clear. It has been made obsolete in the current `dev` version due to a change in the clustering algorithm.

**Comment by Sebastien-Raguideau** [comment]
Thanks for the answer. It does seem to come from my pytorch installation.
It can't be RAM I got 3T and nothing was running at that time. Also Ram usage does not seems super important ~ 20G max
I'll run some test on different server and see if I can isolate the origin of the issue. Also I'll switch to dev.

**Comment by jakobnissen** [comment]
For reference, running 49 samples for 300 epochs using a dataset of 1000 contigs takes 2 minutes, 20 seconds on my 14 inch laptop without GPU.

**Comment by Sebastien-Raguideau** [comment]
Yeah, something is not right on that server. Either that or there really is a downside to 90 cpu. I'll look into it. 
I think the primary issue is can be closed and I'll update here what i find.
