### ISSUE TITLE
Error stating that improper characters are present when they are not

### ISSUE THREAD

**Issue by MrCrotalusatrox** [jakobnissen/vamb#2]
Hello, 

I've tried to run VAMB several ways, but I keep getting the same error message telling me that I have improper characters in the fasta file produced by metaspades. The mapping was done against these assemblies with BWA, assembly with metaspades. In the first example command below, i've filtered the assembly FASTA using "seqtk seq -L2000" to remove contigs <2kb . This does change the FASTA format to list the whole sequence on one line. In the second command i'm running it on the FASTA file exactly as it was produced by metaspades. I get the same message with either command but the improper character is listed on different lines. When I got to that line (e.g. line 6), there are no characters other than AGCTN, so i'm not sure what VAMB is complaining about. 

I've also run this command to see if there are any characters other than AGCTN and I see none: 

grep -v "^>" temp_contigsOver2000bp_metaspades_seqpurged_SB9152_S1_scaffolds.fasta | sed 's/A//g' | sed 's/T//g' | sed 's/G//g' | sed 's/C//g' | sed "s/N//g" > temp.txt

The only thing in temp.txt is invisible characters...end line characters, maybe?

Any help that you could give would be appreciated. I'm happy to email you the files i'm using. 

**The command(s) I ran:**

run.py temp_contigsOver2000bp_metaspades_seqpurged_SB9152_S1_scaffolds_VAMB_output temp_contigsOver2000bp_metaspades_seqpurged_SB9152_S1_scaffolds.fasta bammMapping_SB9152_S1Assembly_scaffolds.seqpurged_SB91*.bam -m 2000

**The error:**

Traceback (most recent call last):
  File "/srv/sw/miniconda3/envs/vamb/bin/run.py", line 311, in <module>
    logfile=logfile)
  File "/srv/sw/miniconda3/envs/vamb/bin/run.py", line 132, in main
    tnfs, contignames = calc_tnf(outdir, fastapath, mincontiglength, logfile)
  File "/srv/sw/miniconda3/envs/vamb/bin/run.py", line 28, in calc_tnf
    preallocate=True)
  File "/srv/sw/miniconda3/envs/vamb/lib/python3.6/site-packages/vamb/parsecontigs.py", line 81, in read_contigs
    return _read_contigs_preallocated(filehandle, minlength, dtype)
  File "/srv/sw/miniconda3/envs/vamb/lib/python3.6/site-packages/vamb/parsecontigs.py", line 39, in _read_contigs_preallocated
    for entry in entries:
  File "/srv/sw/miniconda3/envs/vamb/lib/python3.6/site-packages/vamb/vambtools.py", line 243, in byte_iterfasta
    raise ValueError("Non-ACGTN in line {}: '{}'".format(linenumber + 1, bad_character))
ValueError: Non-ACGTN in line 6: 'N'

**Comment by jakobnissen** [comment]
Hey @MrCrotalusatrox 

Thanks for using Vamb this early, it's nice to catch all the bugs as soon as possible. I'll roll out a series of test scripts over the next days to hopefully catch some more and make the user experience more tolerable.

I've found the bug and fixed it in the latest commit - Vamb now takes all IUPAC ambiguous DNA letters, but I simply forgot to add "N". Would you kindly re-clone the repository and check that it works now?

**Comment by MrCrotalusatrox** [comment]
Hi Jakob, 

I have re-dowloaded your latest commit and attempted to run it. It seems to work now but what is the expected output? I have the following files: clusters.tsv,  latent.npz,  log.txt,  model.pt,  rpkm.npz, and tnf.np . However, I don't have a set of bins. Am I meant to parse the assembly myself 
 using the clusters file? 

Also, the script I have is called run.py and the flag for ignoring short contigs appears to be -m instead of minlength . Is that correct? If these have changed, it would be nice if you updated your github page which uses a different run-script name and flag names. 

One more issue...I wouldn't suggest that you advise people to remap their reads to a subset of large contigs. I think it's more proper to map to the whole assembly, especially using BWA, to make sure the reads can find their best mapping. Otherwise those reads will be placed somewhere on the remaining contigs and may throw off coverage...to what extent that's true, I don't know, but it seems potentially problematic. I believe binners like MetabatV2 even apply a filter to the BAM files when calculating coverage to make sure that reads are well mapped, as apposed to the 20bp of a 150bp read that bwa is willing to mark as mapped.

Best regards, 

Steve

**Comment by jakobnissen** [comment]
Dear @MrCrotalusatrox 

Yes, the six files you listed are the expected output files. We do not create the FASTA bins themselves for two reasons: First, for some applications, the bins may be more annoying and harder to parse than the `clusters.tsv` file. Second, we have elected to output all DNA sequences in `clusters.tsv`, so the resulting number of clusters can be very large. See issue #4 . If you want to produce a directory of bins using the `clusters.tsv`, you can use the convenience function `vamb.vambtools.write_bins`. See the tutorial at `doc/tutorial.html` chapter "Postprocessing the bins" for more information (hint: You can use `vamb.clusters.read_clusters` to read in `clusters.tsv`).

The expected output files ought to be listed in the README.md (GitHub front page). I have added it, and also updated the run-script name and argument name as you suggested.

Lastly, to your issue with remapping onto the subset of large contigs: I disagree with you, although the best way to map is a complicated issue. Broadly, we actually don't want each read to map to just the best contig, because what will then happen is that each read solely map to the contig that it is part of, so all reads from sample A will only map to contigs from sample A. In that situation, there is no such thing as co-abundance.
The better situation would be that each read maps to each contig if they are sufficiently similar, so that reads may map to many contigs. This has its own problems (the abundance of highly conserved sequences gets thrown off), but is preferable. For that reason, Vamb also parses the extra hits marked with "XA" in the BAM-file.
The usual situation with BWA is that good mappings to short contigs prevent decent mappings to long contigs. This is detrimental to binning, because the short contigs are basically unbinnable, and the decent hit to the long contig does probably come from homology (remember - the point of co-abundance is that each read truly "belongs" to multiple contigs).

You are right that for applications like this, BWA is much too generous in what it accepts as hits, and this has the potential to throw off abundance. In an ideal world, Vamb minded its own business binning, and trusted the aligner to do the alignment. After all, the people who make aligners probably know more about how to judge trustworthy alignments than I do. The alternative, namely Vamb selectively picking and choosing the alignments is mostly unworkable (because it would necessitate us to second-guess the choices of every single alignment algorithm). At the end of the day, Vamb only has the alignment information the aligner gives it, and so must trust it on a fundamental level. However, we are not in an ideal world (how many users have the time to think about all this in detail?), so Vamb by default *does* automatically filter hits away with an alignment score less than 50.

I'm closing this issue because the original issue is resolved. However, feel free to open another issue if you have other points or suggestions.
