### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by SilasK** [jakobnissen/vamb#3]
I tried vmab on osx, 
Error when importing. 

```
>>> import sys
>>> sys.path.append("../GitHub/")
>>> import vamb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../GitHub/vamb/__init__.py", line 35, in <module>
    from . import vambtools
  File "../GitHub/vamb/vambtools.py", line 224
    raise TypeError(errormsg) from None
                                 ^
SyntaxError: invalid syntax


```

Error when running run.py

by the way, you can make run.py executable already in the github. 
`chmod +x run.py` 

```
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1297.
./run.py: line 11: syntax error near unexpected token `os.path.dirname'
./run.py: line 11: `sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))'
```

Can you make a release when you are ready?

**Comment by jakobnissen** [comment]
Dear @SilasK 

It appears you're running Vamb with Python2 rather than Python3. Vamb only works with the latter.
I've not changed the README.md to state that Python3 is needed, and attempting to import Vamb using any version of Python before 3.5 now results in an error complaining about the Python version.

I won't make `run.py` executable, partly because the path for the Python executable may vary between users, so the user would need to specify this manually anyway.

And yes, I'll make sure to release Vamb soon! I'm currently writing some test scripts, which should catch some of the lingering bugs. Also, I'll wait a bit before releasing before I get feedback from a few people telling whether it works.

I'm closing this issue. Thank you for submitting it and making Vamb better!
